# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Georgi Doig
email: georgi@projectresponsive.com
description: "Hello, it's me"
baseurl: /portfolio
url: "http://projectresponsive.com"
tagline: "georgi doig portfolio"
twitter_username: georgidoig
github_username:  georgidoig
collections:
 projects:
  output: true
  permalink: /projects/:title

# Build settings
markdown: kramdown
permalink: /blog/:title


#gems
gems:
- susy
- breakpoint
